# Generated by Django 3.2 on 2022-01-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahakari_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_info',
            name='address',
            field=models.CharField(max_length=100, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='account_info',
            name='balance',
            field=models.IntegerField(null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='account_info',
            name='dob',
            field=models.DateField(blank=b'I01\n', null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='account_info',
            name='phone',
            field=models.IntegerField(null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
