# Generated by Django 3.2 on 2022-01-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahakari_app', '0002_auto_20220125_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_info',
            name='account_number',
            field=models.IntegerField(null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
