# Generated by Django 4.0.4 on 2022-04-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahakari_app', '0004_auto_20220204_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_info',
            name='pincode',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
