# Generated by Django 4.0.4 on 2022-04-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahakari_app', '0005_account_info_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_info',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='account_info',
            name='pincode',
        ),
    ]
