# Generated by Django 4.0.4 on 2022-04-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahakari_app', '0006_remove_account_info_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_info',
            name='balance',
            field=models.IntegerField(null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
