# Generated by Django 4.0.4 on 2022-04-20 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahakari_app', '0007_account_info_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.TextField(null=b'I01\n')),
                ('account_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sahakari_app.account_info')),
            ],
        ),
    ]
