# Generated by Django 4.0.4 on 2022-04-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahakari_app', '0008_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_info',
            name='pdf',
            field=models.FileField(default=False, upload_to='static/media'),
        ),
    ]
